import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "#/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

const raleway = Raleway({
  weight: ['100', '900'],
  style: ['normal', 'italic'],
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <head>
        <script src="js/paged.polyfill.js" async></script>
      </head>
      <body className={" " + inter.className}>
        <div id="pagedjs-preview"></div>
        {children}
      </body>
    </html>
  );
}
